#!/usr/bin/env bash

set -e

reboot_confirm() {
    SELECTION=$(echo -e "Confirm\nCancel" | fuzzel -d -p " " -w 20 -l 2)

    case $SELECTION in
        "Confirm")
            notify-send "Rebooting..."
            exec systemctl reboot
            ;;
        *)
            ;;
    esac
}

shutdown_confirm() {
    SELECTION=$(echo -e "Confirm\nCancel" | fuzzel -d -p " " -w 20 -l 2)
    case $SELECTION in
        Confirm)
            notify-send "Shutting down..."
            exec systemctl poweroff
            ;;

        *)
            ;;
    esac
}

SELECTION=$(echo -e "Reboot\nShut Down" | fuzzel -d -p " " -w 20 -l 3)

case $SELECTION in
"Reboot")
    reboot_confirm
    ;;
"Shut Down")
    shutdown_confirm
    ;;
*)
    ;;
esac
