#!/usr/bin/env bash

# tmux-sessionizer
# Credit: [ThePrimeagen](https://github.com/ThePrimeagen)
# Commit: https://github.com/ThePrimeagen/.dotfiles/blob/62eb982a12d75abbdeb6d679504382365456d75c/bin/.local/scripts/tmux-windowizer

IFS=":" read -a PROJECT_FIND_PATH <<< $PROJECT_PATH

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find $PROJECT_FIND_PATH -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
