[colors]
ansi = [
'#c2c2c2',
'#333333',
'#9a9a9a',
'#868686',
'#727272',
'#aeaeae',
'#4a4a4a',
'#5e5e5e',
]
brights = [
'#5e5e5e',
'#333333',
'#9a9a9a',
'#868686',
'#727272',
'#aeaeae',
'#4a4a4a',
'#7c7c7c',
]
cursor_bg = '#868686'
cursor_border = '#868686'
cursor_fg = '#cccccc'
foreground = '#868686'
background = '#cccccc'

[colors.indexed]

[metadata]
name = 'E-ink (Light)'
origin_url = 'https://github.com/e-ink-colorscheme'
