[colors]
ansi = [
	'#5c6a72',
	'#f85552',
	'#8da101',
	'#dfa000',
	'#3a94c5',
	'#df69ba',
	'#35a77c',
	'#d8d3ba',
]
background = '#f3ead3'
brights = [
	'#5c6a72',
	'#f85552',
	'#8da101',
	'#dfa000',
	'#3a94c5',
	'#df69ba',
	'#35a77c',
	'#d8d3ba',
]
cursor_bg = '#5c6a72'
cursor_border = '#5c6a72'
cursor_fg = '#f3ead3'
foreground = '#5c6a72'

[colors.indexed]

[metadata]
name = 'Everforest Light (Soft)'
origin_url = 'https://github.com/frdwin/Everforest-Wezterm'
