update_check_interval 72

font_family      family="DepartureMono Nerd Font"
# font_family      family="GeistMono Nerd Font"
# font_family      family="BlexMono Nerd Font"
# font_family      family="CommitMonoTK Nerd Font"
# font_family      family="Liga SFMono Nerd Font"

font_size 13.0

font_features none

# Silence!!
enable_audio_bell no
# But notify me when a task is completed
notify_on_cmd_finish unfocused 10 notify

# Tab Bar
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

# No closing the terminal accidently
map ctrl+shift+q noop
map ctrl+shift+w noop

# Darwin
# macos_thicken_font 0.25
macos_option_as_alt both

# Theme
include ./themes/everforest/Everforest Light Soft.conf
